# Generated by Django 4.0 on 2021-12-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='frequency',
            field=models.FloatField(verbose_name='processor frequency'),
        ),
    ]
