# Generated by Django 4.0 on 2021-12-19 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_processor_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processor',
            name='computer',
        ),
        migrations.AddField(
            model_name='computer',
            name='processor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='computers', to='app.processor'),
        ),
    ]
